---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
verifier:
  name: inspec

platforms:
  - name: bento/debian-9.4
  - name: bento/ubuntu-16.04
  - name: bento/centos-7.4

suites:
  - name: default
    run_list:
      - recipe[proftpd-ii::force_ssh_keys]
      - recipe[proftpd-ii::example_lwrp]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
